import sys
import re
import os
import getpass
from pathlib import Path

# Check if Colors is available in the expected path, otherwise mock it
try:
    from src.utils.colors import Colors
except ImportError:
    class Colors:
        RESET = ""
        BOLD = ""
        CYAN = ""
        GREEN = ""
        YELLOW = ""
        RED = ""
        GREY = ""
        @classmethod
        def colorize(cls, text, color): return text

def _select_provider() -> str:
    """Prompt user to select an email provider."""
    print(f"\n{Colors.CYAN}Step 1: Choose your email provider{Colors.RESET}")
    print("  1. Gmail (Recommended)")
    print("  2. Proton Mail (Requires Bridge)")
    print("  3. Outlook (Business Only)")
    print("  4. Skip (Manually edit .env)")

    while True:
        try:
            choice = input(f"\n{Colors.BOLD}Select provider [1-4]: {Colors.RESET}").strip()
            if choice in ('1', '2', '3', '4'):
                return choice
            print(f"{Colors.YELLOW}Invalid choice. Please enter 1, 2, 3, or 4.{Colors.RESET}")
        except EOFError:
            return '4'

def _get_credentials(choice: str, provider_name: str) -> tuple[str, str]:
    """Prompt user for email and app secret."""
    print(f"\n{Colors.CYAN}Step 2: Configure {provider_name} Credentials{Colors.RESET}")

    try:
        email = input(f"Enter your {provider_name} email address: ").strip()
        while not email:
            print(f"{Colors.YELLOW}Email is required.{Colors.RESET}")
            email = input(f"Enter your {provider_name} email address: ").strip()

        # Context-specific help
        if choice == '1': # Gmail
            print(f"\n{Colors.GREY}Note: Use an App Password, not your login password.")
            print(f"Generate one at: Google Account -> Security -> 2-Step Verification -> App passwords{Colors.RESET}")
        elif choice == '2': # Proton
            print(f"\n{Colors.GREY}Note: Use the password generated by Proton Mail Bridge.")
            print(f"Find it in: Proton Mail Bridge app -> Mailbox details{Colors.RESET}")
        elif choice == '3': # Outlook
            print(f"\n{Colors.GREY}Note: Personal Outlook accounts are not supported.")
            print(f"Business accounts may require an App Password if MFA is enabled.{Colors.RESET}")

        app_secret = getpass.getpass(f"Enter your {provider_name} app password: ").strip()
        while not app_secret:
            print(f"{Colors.YELLOW}Password is required.{Colors.RESET}")
            app_secret = getpass.getpass(f"Enter your {provider_name} app password: ").strip()

        return email, app_secret
    except EOFError:
        return "", ""

def _generate_config_content(template_content: str, provider_key: str, email: str, app_secret: str) -> str:
    """Generate configuration content by replacing template variables."""
    content = template_content

    # Helper to disable other providers
    all_providers = ['GMAIL', 'PROTON', 'OUTLOOK']
    for provider in all_providers:
        if provider == provider_key:
            content = re.sub(f"{provider}_ENABLED=.*", f"{provider}_ENABLED=true", content)
        else:
            content = re.sub(f"{provider}_ENABLED=.*", f"{provider}_ENABLED=false", content)

    # Set email for selected provider
    content = re.sub(f"{provider_key}_EMAIL=.*", f"{provider_key}_EMAIL={email}", content)

    # Set app_secret safely
    def replace_secret(match):
        return f"{provider_key}_APP_PASSWORD={app_secret}"

    content = re.sub(f"{provider_key}_APP_PASSWORD=.*", replace_secret, content)

    return content

def run_setup_wizard(config_file: str = ".env", template_file: str = ".env.example") -> bool:
    """
    Run an interactive setup wizard to configure the application.
    Returns True if setup was successful, False otherwise.
    """

    if not Path(template_file).exists():
        print(f"{Colors.RED}Error: Template file '{template_file}' not found.{Colors.RESET}")
        return False

    print(f"\n{Colors.BOLD}🧙 Welcome to the Email Security Pipeline Setup Wizard! 🧙{Colors.RESET}")
    print(f"{Colors.GREY}Let's get your environment configured quickly.{Colors.RESET}")

    # 1. Select Provider
    choice = _select_provider()
    if choice == '4':
        return False

    provider_map = {
        '1': ('GMAIL', 'Gmail'),
        '2': ('PROTON', 'Proton Mail'),
        '3': ('OUTLOOK', 'Outlook')
    }
    selected_key, selected_name = provider_map[choice]

    # 2. Get Credentials
    email, app_secret = _get_credentials(choice, selected_name)
    if not email or not app_secret:
        return False

    # 3. Read Template
    try:
        with open(template_file, 'r') as f:
            template_content = f.read()
    except Exception as e:
        print(f"{Colors.RED}Error reading template: {e}{Colors.RESET}")
        return False

    # 4. Generate Config
    new_content = _generate_config_content(template_content, selected_key, email, app_secret)

    # 5. Write Config
    try:
        # Create file with restrictive permissions (600)
        # Using os.open to set mode atomically if possible, or chmod after
        fd = os.open(config_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, 'w') as f:
            f.write(new_content)

        print(f"\n{Colors.GREEN}✔ Configuration saved to {config_file}{Colors.RESET}")
    except Exception as e:
        print(f"{Colors.RED}Error writing config: {e}{Colors.RESET}")
        return False

    print(f"\n{Colors.BOLD}Next Steps:{Colors.RESET}")
    print("1. Review .env to ensure settings are correct.")
    print("2. Run the pipeline!")

    return True
