name: Bandit
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Install dependencies
        run: pip install bandit bandit-sarif-formatter

      - name: Run Bandit Scan
        run: bandit -f sarif -o results.sarif -r . --exit-zero --ini .bandit

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: results.sarif
          path: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@codeql-bundle-v2.25.5 # codeql-bundle-v2.25.5
        with:
          sarif_file: results.sarif
